// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 审计日志（含操作者用户名，便于展示）。
 */
export type AuditLog = { id: string, actor_id: string | null, actor_username: string | null, action: string, entity_type: string, entity_id: string | null, 
/**
 * JSON 文本形式的变更 diff。
 */
changes: string | null, ip: string | null, user_agent: string | null, created_at: string, };
