// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 远程连接相关信息数据库行 / DTO。
 */
export type CustomerRemoteConnection = { id: string, customer_id: string, name: string, wemol_username: string | null, wemol_password: string | null, connection_info: string | null, created_at: string, updated_at: string, };
