// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserOptionDto } from "./UserOptionDto";

/**
 * 客户 + 汇总 DTO（对外）。
 */
export type CustomerSummaryDto = { id: string, name: string, short_name: string | null, industry: string | null, contact_name: string | null, contact_phone: string | null, contact_email: string | null, address: string | null, notes: string | null, created_at: string, updated_at: string, 
/**
 * 已完成的维护记录数。
 */
maintenance_count: number, 
/**
 * 最近一次完成维护的时间（ISO8601）。
 */
last_maintained_at: string | null, 
/**
 * 在用部署实例数。
 */
active_deployments: number, 
/**
 * 指派的运维人员。
 */
assigned_users: Array<UserOptionDto> | null, };
