// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 客户文件（对外，不含磁盘 storage_key）。
 */
export type CustomerFile = { id: string, customer_id: string, folder_path: string, filename: string, size_bytes: number, mime_type: string | null, uploaded_by: string | null, uploaded_by_username: string | null, created_at: string, };
