// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 部署实例数据库行 / DTO（字段一致，直接复用）。
 */
export type Deployment = { id: string, customer_id: string, product: string, version: string | null, environment: string | null, go_live_date: string | null, status: string, notes: string | null, created_at: string, updated_at: string, };
