// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 列表项：维护记录 + 客户名 + 负责人用户名（便于直接展示）。
 */
export type MaintenanceListItem = { id: string, customer_id: string, customer_name: string, deployment_id: string | null, title: string, type: string, status: string, assignee_id: string | null, assignee_username: string | null, maintained_at: string, completed_at: string | null, created_at: string, };
