// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 维护记录完整行 / DTO（详情用）。
 */
export type MaintenanceRecord = { id: string, customer_id: string, deployment_id: string | null, title: string, type: string, status: string, assignee_id: string | null, content: string | null, result: string | null, maintained_at: string, completed_at: string | null, created_by: string | null, created_at: string, updated_at: string, };
