// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserOptionDto } from "./UserOptionDto";

/**
 * 列表项：维护记录 + 客户名 + 负责人（便于直接展示）。
 */
export type MaintenanceListItem = { id: string, customer_id: string, customer_name: string, deployment_id: string | null, title: string, type: string, status: string, maintained_at: string, completed_at: string | null, created_at: string, assignees: Array<UserOptionDto> | null, };
