// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 站内通知（列表项，联查客户名便于展示/跳转）。
 */
export type NotificationDto = { id: string, user_id: string, type: string, title: string, body: string | null, customer_id: string | null, customer_name: string | null, read_at: string | null, created_at: string, };
