// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RolePermissions } from "./RolePermissions";

export type RoleResponseDto = { id: string, name: string, description: string | null, permissions: RolePermissions, created_at: string, updated_at: string, };
