// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RolePermissions = { data_scope: string, view_pages: Array<string>, actions: Array<string>, };
