// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 对外 DTO（去掉密码哈希）。
 */
export type UserDto = { id: string, username: string, email: string, role: string, is_active: boolean, created_at: string, };
