// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 简易用户选项 DTO（供指派或下拉选择使用）。
 */
export type UserOptionDto = { id: string, username: string, };
